<?php
    include_once("../config/database.php");

    $sede = $_POST;

    $resultado = $mysqli->query('SELECT EQUIPO.NOMBRE_EQUIPO, CONCAT("Perfil " , PERFIL_EQUIPO.ID_PERFIL_EQUIPO) as "PERFIL",  CONCAT(FUNCIONARIO.PRIMERNOMBRE_FUNCIONARIO , " " , FUNCIONARIO.PRIMERAPELLIDO_FUNCIONARIO , " " , FUNCIONARIO.SEGUNDOAPELLIDO_FUNCIONARIO) as "NOMBRE_FUNCIONARIO", DATE_FORMAT( ASIGNACION.FECHAINICIO_ASIGNACION,"%d/%m/%Y") AS "FECHA_INICIO", DATE_FORMAT( ASIGNACION.FECHAFINAL_ASIGNACION,"%d/%m/%Y") AS "FECHA_FIN" FROM EQUIPO INNER JOIN PERFIL_EQUIPO on PERFIL_EQUIPO.ID_PERFIL_EQUIPO = EQUIPO.ID_PERFIL_EQUIPO INNER JOIN ASIGNACION on ASIGNACION.ID_EQUIPO = EQUIPO.ID_EQUIPO INNER JOIN PROGRAMAFUNCIONARIO ON PROGRAMAFUNCIONARIO.ID_PROGRAMAFUNCIONARIO = ASIGNACION.ID_PROGRAMAFUNCIONARIO INNER JOIN FUNCIONARIO ON PROGRAMAFUNCIONARIO.RUT_FUNCIONARIO = FUNCIONARIO.RUT_FUNCIONARIO INNER JOIN PROGRAMA ON PROGRAMA.ID_PROGRAMA = PROGRAMAFUNCIONARIO.ID_PROGRAMA INNER JOIN FACULTAD ON FACULTAD.ID_FACULTAD = PROGRAMA.ID_FACULTAD INNER JOIN SEDE ON SEDE.ID_SEDE = FACULTAD.ID_SEDE WHERE SEDE.NOMBRE_SEDE = "' . $sede['sede'] . '"');

    $i = 0;
    $resultado->data_seek(0);
    $arr    =   array();
    while ($item = $resultado->fetch_assoc()) {
        $arr["data"][$i]['NOMBRE_EQUIPO']  = $item['NOMBRE_EQUIPO'] ;
        $arr["data"][$i]['PERFIL']  = $item['PERFIL'] ;
        $arr["data"][$i]['NOMBRE_FUNCIONARIO']  = $item['NOMBRE_FUNCIONARIO'] ;
        $arr["data"][$i]['FECHA_INICIO']  = $item['FECHA_INICIO'] ;
        $arr["data"][$i]['FECHA_FIN']  = $item['FECHA_FIN'] ;
        $i++;
    }

    $mysqli->close();

 
    echo json_encode($arr);


    ?>


